version: '3.8'

services:
  traefik:
    image: traefik:v2.3.2
    command: --api --docker --docker.domain=traefik.local --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
    networks:
      - web

networks:
  web:
    driver: bridge
